### ISSUE TITLE
Find third person for project; meet bureaucracy requirements

### ISSUE THREAD

**Issue by StanczakDominik** [okmechak/SocSIM#7]

**Comment by okmechak** [comment]
W tej chwili juz jest Aleksandra Jankowska, jeszcze jedna chetna osoba niestety okazała się z 1go stopnia studiow.

Tez przez USOS wpisal sie Grzegoz Skóra, czekam na opdpowiedz od niego mailową.

**Comment by okmechak** [comment]
Grzegoz juz w zespole
